language: java
branches:
  only:
  - master
  - "/^release-[0-999].[0-999]$/"
  - develop
notifications:
  email:
    recipients:
    - r.roca@alumnos.upm.es
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.organization=rrocamar-github -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key:
    secure: QvLkYt2Jv1xAUaU+UKOdjDSkvHoFZB+VIQ/erm7BKlXlrrxP+LR3N1fMc3KXQPiEhn9aUDQH4pIKAvvXHqW8TrUtoX8DdSzgqVIcqDCFCnxNVExscbZhQAQwbwHBCC3J3XyIGielTsg41ewnm/t9DNeHMSJkaKlidyq5yyceryLmDozCE+5LhaZrW+QBn5x55xpimFAGy/JKIIywqr3a6pj73PoaAwZ21T5MNv5PJd4W7XLFs3jTZdSSEM3oLN6/49HoiASv21EQMCpawPi1LSDrrndDrbbjEXecCzDmb+S0Ca+84B1k0PmZF3zqYSegq/KeQCEG76Dv/TjVpJ2wO/i/Orfuf14jO1AHBP/hy7+i2irXAvXIqSuBY5eG6ENvz7j41xt+J3OtU3MvZh0tvuJDH82vm+OC7P+lBY8610jbe6Uf3u9dbb362SwWLPHoGxGkeWg8ccXvkBQ+UILxOBn6GYDleMlJpK1qA4xs1T6N36mpVCTc3SAqrRKe1J2SzNL/2X8zIfcnxA11N9a9f06xvvcLl6v7oNaoQQsYIApFtpaIRq4wcy9IERCVa8EK4A62XYW4uzfZ4CFPx3VpIW0BUei435Yl9+7dLjmEumT53Qe6gtTnum7mMrmaYEjmkg6kO6NspelvdEl5j4qqVMz5MWGvi8WZkedOWnPox5E=
  on:
    branch: master
  app: klondike-api
