language: java
branches:
  only:
    - master
    - "/^release-[0-999].[0-999]$/"
    - develop
notifications:
  email:
    recipients:
      - r.roca@alumnos.upm.es
script:
  #Test unitario y de integracion
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.organization=rrocamar-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR